# Generated by Django 5.1 on 2024-09-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talla',
            name='talla',
            field=models.CharField(max_length=5),
        ),
    ]
